# Generated by Django 4.2.6 on 2023-10-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Phone Number'),
        ),
    ]
