# Generated by Django 4.2.6 on 2023-11-07 12:39

from django.db import migrations, models
import django.db.models.deletion
import realestate.apps.core.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=128, verbose_name='Nickname')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('categories', models.ManyToManyField(through='categories.Grade', to='categories.category', verbose_name='Categories')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.couple', verbose_name='Couple')),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
                'ordering': ['nickname'],
                'unique_together': {('nickname', 'couple')},
            },
            bases=(models.Model, realestate.apps.core.models.ValidateCategoryCoupleMixin),
        ),
    ]
