# Generated by Django 4.2.6 on 2023-11-07 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import realestate.apps.core.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Couple',
                'verbose_name_plural': 'Couples',
                'ordering': ['realtor'],
            },
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Realtor',
                'verbose_name_plural': 'Realtors',
                'ordering': ['user__email'],
            },
        ),
        migrations.CreateModel(
            name='Homebuyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categories', models.ManyToManyField(through='categories.CategoryWeight', to='categories.category', verbose_name='Categories')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.couple', verbose_name='Couple')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Homebuyer',
                'verbose_name_plural': 'Homebuyers',
                'ordering': ['user__email'],
            },
            bases=(models.Model, realestate.apps.core.models.ValidateCategoryCoupleMixin),
        ),
        migrations.AddField(
            model_name='couple',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.realtor', verbose_name='Realtor'),
        ),
    ]
