# Generated by Django 4.2.6 on 2023-10-29 14:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import realestate.apps.core.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=128, verbose_name='Summary')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['summary'],
            },
        ),
        migrations.CreateModel(
            name='CategoryWeight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.PositiveSmallIntegerField(help_text='0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Weight')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category Weight',
                'verbose_name_plural': 'Category Weights',
                'ordering': ['category', 'homebuyer'],
            },
        ),
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Couple',
                'verbose_name_plural': 'Couples',
                'ordering': ['realtor'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Score')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['homebuyer', 'house', 'category', 'score'],
            },
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Realtor',
                'verbose_name_plural': 'Realtors',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=128, verbose_name='Nickname')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('categories', models.ManyToManyField(through='core.Grade', to='core.category', verbose_name='Categories')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.couple', verbose_name='Couple')),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
                'ordering': ['nickname'],
                'unique_together': {('nickname', 'couple')},
            },
            bases=(models.Model, realestate.apps.core.models.ValidateCategoryCoupleMixin),
        ),
        migrations.CreateModel(
            name='Homebuyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categories', models.ManyToManyField(through='core.CategoryWeight', to='core.category', verbose_name='Categories')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.couple', verbose_name='Couple')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Homebuyer',
                'verbose_name_plural': 'Homebuyers',
                'ordering': ['user__username'],
            },
            bases=(models.Model, realestate.apps.core.models.ValidateCategoryCoupleMixin),
        ),
        migrations.AddField(
            model_name='grade',
            name='homebuyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.homebuyer', verbose_name='Homebuyer'),
        ),
        migrations.AddField(
            model_name='grade',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.house', verbose_name='House'),
        ),
        migrations.AddField(
            model_name='couple',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.realtor', verbose_name='Realtor'),
        ),
        migrations.AddField(
            model_name='categoryweight',
            name='homebuyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.homebuyer', verbose_name='Homebuyer'),
        ),
        migrations.AddField(
            model_name='category',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.couple', verbose_name='Couple'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('house', 'category', 'homebuyer')},
        ),
        migrations.AlterUniqueTogether(
            name='categoryweight',
            unique_together={('homebuyer', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('summary', 'couple')},
        ),
    ]
