# Generated by Django 4.2.6 on 2023-10-29 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['summary'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='categoryweight',
            options={'ordering': ['homebuyer', 'category'], 'verbose_name': 'Category Weight', 'verbose_name_plural': 'Category Weights'},
        ),
        migrations.AlterModelOptions(
            name='couple',
            options={'ordering': ['realtor'], 'verbose_name': 'Couple', 'verbose_name_plural': 'Couples'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['homebuyer', 'house', 'category', 'score'], 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
        migrations.AlterModelOptions(
            name='homebuyer',
            options={'ordering': ['user__username'], 'verbose_name': 'Homebuyer', 'verbose_name_plural': 'Homebuyers'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['nickname'], 'verbose_name': 'House', 'verbose_name_plural': 'Houses'},
        ),
        migrations.AlterModelOptions(
            name='realtor',
            options={'ordering': ['user__username'], 'verbose_name': 'Realtor', 'verbose_name_plural': 'Realtors'},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('summary', 'couple')},
        ),
        migrations.AlterUniqueTogether(
            name='categoryweight',
            unique_together={('homebuyer', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('house', 'category', 'homebuyer')},
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together={('nickname', 'couple')},
        ),
    ]
