# Generated by Django 4.2.6 on 2023-11-03 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryweight',
            name='weight',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Unimportant'), (2, 'Below Average'), (3, 'Average'), (4, 'Above Average'), (5, 'Important')], default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Above Average'), (5, 'Excellent')], default=3, verbose_name='Score'),
        ),
    ]
