# Generated by Django 4.2.6 on 2023-11-09 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0001_initial'),
        ('categories', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='homebuyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.homebuyer', verbose_name='Homebuyer'),
        ),
        migrations.AddField(
            model_name='grade',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.house', verbose_name='House'),
        ),
        migrations.AddField(
            model_name='categoryweight',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='categoryweight',
            name='homebuyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.homebuyer', verbose_name='Homebuyer'),
        ),
        migrations.AddField(
            model_name='category',
            name='couple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.couple', verbose_name='Couple'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('house', 'category', 'homebuyer')},
        ),
        migrations.AlterUniqueTogether(
            name='categoryweight',
            unique_together={('homebuyer', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('summary', 'couple')},
        ),
    ]
