# Generated by Django 4.2.6 on 2023-11-09 01:54

from django.db import migrations, models
import django.db.models.deletion
import realestate.apps.pending.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCouple',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.realtor', verbose_name='Realtor')),
            ],
            options={
                'verbose_name': 'Pending Couple',
                'verbose_name_plural': 'Pending Couples',
                'ordering': ['realtor'],
            },
        ),
        migrations.CreateModel(
            name='PendingHomebuyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(error_messages={'unique': 'A user with this email already exists.'}, max_length=254, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('registration_token', models.CharField(default=realestate.apps.pending.models._generate_registration_token, editable=False, max_length=64, unique=True, verbose_name='Registration Token')),
                ('pending_couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pending.pendingcouple', verbose_name='Pending Couple')),
            ],
            options={
                'verbose_name': 'Pending Homebuyer',
                'verbose_name_plural': 'Pending Homebuyers',
                'ordering': ['email'],
            },
        ),
    ]
